### ISSUE TITLE
Examens kunnen onderscheiden

### ISSUE THREAD

**Issue by peter-somers** [lensmedia/examentheorie.nl-public#2]
Richard wil graag de "echte" examens kunnen onderscheiden van de rest. Dat kan nu niet, want ook de toetsen kunnen examentype "exam" hebben. Kunnen we een extra flag maken die we kunnen toevoegen?

**Comment by jennevdmeer** [comment]
Verkeerde repo dit is public (voor wiki), verplaats naar andere
